language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install gcc-4.7
  - sudo apt-get install libboost-all-dev
  - sudo rm /usr/bin/gcc
  - sudo ln -s /usr/bin/gcc-4.7 /usr/bin/gcc

script:
  - mkdir bin
  - cd bin
  - cmake ..
  - make
  - ./run_tests