language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libboost-all-dev

script:
  - mkdir bin
  - cd bin
  - cmake ..
  - make
  - ./run_tests